---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---


## Loading and preprocessing the data
library(data.table)
library(ggplot2)

fileURL <- "https://d396qusza40orc.cloudfront.net/repdata%2Fdata%2Factivity.zip"
download.file(fileURL,destfile = "./2Factivity.zip")
if(!file.exists('activity.csv')){unzip('2Factivity.zip')}
activityData <- read.csv('activity.csv')


## What is mean total number of steps taken per day?
##-----------------------------------------------
stepsByDay <- tapply(activityData$steps, activityData$date, sum, na.rm=TRUE)

##-------------------------------------------------
qplot(stepsByDay, xlab = 'Total Steps per Day', ylab = 'Frequency of steps' , binwidth = 650)

##-----------------------------------------------
MeanStepsByDay <- mean(stepsByDay)
MedianStepsByDay <- median(stepsByDay, na.rm = TRUE)


## What is the average daily activity pattern?
averages <- aggregate(x=list(steps=activityData$steps), by=list(interval=activityData$interval),
                      FUN=mean, na.rm=TRUE)

ggplot(data=averages, aes(x=interval, y=steps)) +
  geom_line() +
  xlab("5-minute interval") +
  ylab("average number of steps taken")

##------------------------------------------
averages[which.max(averages$steps),]



## Imputing missing values
missing <- is.na(activityData)
table(missing)

##------------------------------------------
fill.value <- function(steps, interval) {
  filled <- NA
  if (!is.na(steps))
    filled <- c(steps)
  else
    filled <- (averages[averages$interval==interval, "steps"])
  return(filled)
}
filled.data <- data
filled.data$steps <- mapply(fill.value, filled.data$steps, filled.data$interval)
filled.data

##------------------------------------------

total.steps <- tapply(filled.data$steps, filled.data$date, FUN=sum)
qplot(total.steps, binwidth=1000, xlab="total number of steps taken each day")
mean(total.steps)
median(total.steps)


## Are there differences in activity patterns between weekdays and weekends?
## ------------------------------------------------------------------------
weekday.or.weekend <- function(date) {
  day <- weekdays(date)
  if (day %in% c("Monday", "Tuesday", "Wednesday", "Thursday", "Friday"))
    return("weekday")
  else if (day %in% c("Saturday", "Sunday"))
    return("weekend")
  else
    stop("invalid date")
}
filled.data$date <- as.Date(filled.data$date)
filled.data$day <- sapply(filled.data$date, FUN=weekday.or.weekend)


## ------------------------------------------------------------------------
averages <- aggregate(steps ~ interval + day, data=filled.data, mean)
ggplot(averages, aes(interval, steps)) + geom_line() + facet_grid(day ~ .) +
  xlab("5-minute interval") + ylab("Number of steps")